name: Ci Cmake

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: get
        uses: actions/checkout@v4

      - name: configure
        run: cmake -S . -B build

      - name: build
        run: cmake --build build --config Release

      - name: test hello_world
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ./build/hello_world_application/Release/hello_world.exe
          else
            ./build/hello_world_application/hello_world
          fi
        shell: bash

      - name: test solver
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "1 -13 42" | ./build/solver_application/Release/solver.exe
          else
            echo "1 -13 42" | ./build/solver_application/solver
          fi
        shell: bash
        
