name: Ci Cmake

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [gcc, clang, msvc]
        exclude:
          - os: ubuntu-latest
            compiler: msvc
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang

    steps:
      - name: get
        uses: actions/checkout@v4

      - name: configure
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            if [[ "${{ matrix.compiler }}" == "clang" ]]; then
              sudo apt-get update && sudo apt-get install -y clang
              cmake -S . -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
            else
              cmake -S . -B build -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
            fi
          else
            cmake -S . -B build
          fi

      - name: build
        run: cmake --build build --config Release

      - name: test hello_world
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ./build/hello_world_application/Release/hello_world.exe
          else
            ./build/hello_world_application/hello_world
          fi
        shell: bash

      - name: test solver
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "1 -13 42" | ./build/solver_application/Release/solver.exe
          else
            echo "1 -13 42" | ./build/solver_application/solver
          fi
        shell: bash
        
